name       : qjackctl
version    : 0.5.5
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/qjackctl/qjackctl/0.5.5/qjackctl-0.5.5.tar.gz : e5eb7b9249ba22f5301645f792eb34e7306b9002594eb945c9941a9586c2ffe7
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
