name       : qjackctl
version    : 0.5.9
release    : 12
source     :
    - https://sourceforge.net/projects/qjackctl/files/qjackctl/0.5.9/qjackctl-0.5.9.tar.gz/download : f3fa7b3c1e28d56632de10c32e978a54f94c29b0239e2b6b2622d4a49ae65ee9
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
