name       : qjackctl
version    : 0.5.4
release    : 6
source     :
    - https://kent.dl.sourceforge.net/project/qjackctl/qjackctl/0.5.4/qjackctl-0.5.4.tar.gz : 982df020a9c3ba3cb4f481236d181f277c64c22b94393b0a2e7fbe91960d2763
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
