name       : qjackctl
version    : 0.6.0
release    : 13
source     :
    - https://github.com/rncbc/qjackctl/archive/qjackctl_0_6_0.tar.gz : 229339dd59977712393412317b6c6d1d6130f4902c20a4b48cf75de48c46131f
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
