name       : qjackctl
version    : 0.4.5
release    : 5
source     :
    - http://kent.dl.sourceforge.net/project/qjackctl/qjackctl/0.4.5/qjackctl-0.4.5.tar.gz : c50da569ec8466ac6cc72c65e2d8212eb9c40149daed0a10fb7795ff9ddc4ab7
license    : GPL-2.0
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
