name       : qjackctl
version    : 0.5.8
release    : 11
source     :
    - https://sourceforge.net/projects/qjackctl/files/qjackctl/0.5.8/qjackctl-0.5.8.tar.gz/download : 5600033bb32ac3e52f03a191cc2e31a27be3be98fdd49ce5481688cce070b0e4
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : QjackCtl is a simple Qt application to control the JACK sound server
description: |
    QjackCtl is a simple Qt application to control the JACK sound server
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
